[platformio]
src_dir = .

[env]
framework = arduino
build_type = release
monitor_speed = 115200

[env:bridge-esp8266-at]
platform = espressif8266@4.2.1
board = esp8285
board_build.f_cpu = 160000000L
build_flags =
  -D MODULE_ESP82XX_ELRS_TX
lib_deps =
  vshymanskyy/Preferences@2.2.2

[env_common_esp32]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board_build.partitions = no_ota.csv

[env:bridge-esp32-pico-at]
extends = env_common_esp32
board = pico32
build_flags =
  -D MODULE_MATEK_MTX_DB30

[env:bridge-esp32c3-at]
extends = env_common_esp32
board = esp32-c3-devkitm-1
build_flags =
  -D MODULE_ESP32C3_ELRS_TX
